### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by markwragg** [microsoft/service-fabric-observer#218]
**Describe the bug**

Fabric Observer fails to get Private Working Set values for processes that names are over a certain length. As a result the Fabric Observer utilities.logs is repeatedly filled with messages like these, resulting in them growing to 150mb a day:

```
2022-06-16 23:59:59.9997--WARN--GetProcessPrivateWorkingSetMbFromPerfCounter: Handled: Unable to get private working set for process examp.proc.xxx.value.somename.nameofprocessis.verylongindeed.process with id 16796. Returning 0.
System.InvalidOperationException: Instance 'examp.proc.xxx.value.somename.nameofprocessis.verylongindeed.process' does not exist in the specified Category.
   at System.Diagnostics.CounterDefinitionSample.GetInstanceValue(String instanceName)
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at FabricObserver.Observers.Utilities.WindowsProcessInfoProvider.GetProcessPrivateWorkingSetMbFromPerfCounter(String procName, Int32 procId) in D:\a\1\s\FabricObserver.Extensibility\Utilities\ProcessInfo\WindowsProcessInfoProvider.cs:line 338
```

Note I have changed the name of the process for confidentiality reasons, but i've kept the length of the string the same. When I look at the counters via Perfmon and go to Process > Working Set - Private > I can see the process instance name there is truncated. It looks like the maximum name length is 67 characters. With my example, you'd see: `examp.proc.xxx.value.somename.nameofprocessis.verylongindeed.proce` as the instance name under perfmon.

**To Reproduce**

Run an executable in Service Fabric with a name that is 68 or more characters long and attempt to monitor its memory usage with Service Fabric Observer.

**Expected behavior**

Service Fabric Observer should ideally be able to monitor processes regardless of their name length, but I guess if the issue here is unsolvable because its a limitation with Perfmon, then Service Fabric Observer should ideally handle the situation in a way that doesn't generate 100s of MBs of logs.

**Screenshots**
Unable to provide.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2019 (1809)

**Additional context**

**Comment by markwragg** [comment]
We were previous using Fabric Observer 3.1.23 and have just upgraded to 3.1.26. The issue was surfaced to us due to the new default monitor of the service fabric logs directory, but I can see the same problem was occurring in 3.1.23, however it generated smaller log files as it was logged as just a single line (again process name has been changed for privacy):

```
2022-06-16 00:00:00.3767--WARN--Unable to get private working set for process examp.proc.xxx.value.somename.nameofprocessis.verylongindeed.process with id 22956. Returning 0.
```

**Comment by GitTorre** [comment]
Thank you for this report. 

I am curious why the process names need to be so long. That is of course your choice (and not really any of my business), but you can see this approach causes issues that are unrelated to FO, besides its logging stack traces (which I can change in the next release to be less verbose, but it is quite useful in debugging, as you can see. The older message is useless if the goal is to understand what went wrong). Perhaps I can add a configuration setting that will allow for specifying verbose vs single line Warning log output.

For now, I recommend that you disable Private Working Set monitoring by AppObserver. This will force FO to use a different approach, Working Set (Private + Shared), which does not employ a perf counter. It will use a Win32 API call. The value will be larger since it is private memory plus memory used by shared components, but you will be accurately informed when your service processes are using too much memory as their private memory is what would account for dynamic growth, especially when they approach "leaking" or over-use that exceeds your threshold. This could be due to some bug in user code, for example (which is one of the things you are monitoring). You can do this today with a version-less, parameter-only application upgrade (so, no need to redeploy FO):

```PowerShell
$appParams = @{ "AppObserverMonitorPrivateWorkingSet" = "false";  }
Start-ServiceFabricApplicationUpgrade -ApplicationName fabric:/FabricObserver -ApplicationParameter $appParams -ApplicationTypeVersion 3.1.26 -UnMonitoredAuto
````

In the meantime, I will investigate how to work around this problem and give you the ability to truncate log output via configuration. Do note that FO can be configured to manage its own log folders so you could decrease the amount of time it waits to clean them up, for example (default is 3 days). See Settings.xml (this requires that you redeploy FO or do a configuration-only upgrade where you will need to bump the versions of Code and Config and Service and App..): 

```XML
    <!-- Optional: Maximum Number of days to store Archived observer log files on disk. 
            This setting spans all ObserverLogger instances (ObserverBase.ObserverLogger), including plugins and ObserverManager. 
            The default value is 0. An empty value or 0 means there is no lifetime constraint. They are immortal files. -->
    <Parameter Name="MaxArchivedLogFileLifetimeDays" Value="3" />
``` 

But the real issue here is related to process naming convention you have employed. The other stuff are side effects of this decision. Again, I will work on making it possible to shut off logging completely or modify the verbosity of Warning/Error level log output via user configuration settings. Let me know how turning off Private Working Set monitoring works out for you. I will also look into why there is a restriction of process name length that is less than MAX_PATH characters on Windows. This seems odd to me. I will do some tests and see if there is a way to work around this restriction. For now, you have a mitigation to try. 

Thanks again for the detailed report. I'm sorry you are running into issues.

**Comment by GitTorre** [comment]
There is a 128 max character limit on InstanceName for perf counters.

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.performancecounter.instancename?view=dotnet-plat-ext-6.0

**Comment by GitTorre** [comment]
The return full working set impl when encountering a process name that exceeds 64 chars is now in place in develop and net6 branches, both of which are tested (per usual).

**Comment by markwragg** [comment]
This all sounds great to me. I will switch to Working Set monitoring to workaround the issue. I like the idea of this being automatic when the process names are over a certain length.

I completely agree the problem here is our process names and I have added a backlog item to get them made shorter, but I think it can be a tricky process to rename services in Service Fabric if you need to also maintain state as I think Service Fabric will treat the renamed services as new ones.

I think the workaround and future mitigation is good, feel free to close this issue if you agree there isn't anything more to do here.

**Comment by GitTorre** [comment]
> FYI I've noticed that despite having `MaxArchivedLogFileLifetimeDays` set to 3 (which it was already by default) I'm seeing 8 days of logs under the C:\fabric_observer_logs\Utilitie directory (the current log and 7 days of ones with a date stamp). 
> 
> 
> 
> Is this expected?

It's actually 7 days default, not 3. I need to modify the comments to reflect that in app manifest. The logger impl should be deleting files over 7 days old.
